title: Editor storytime
hero_image: images/banner.png
description: Create a story that is new each time.
version: 1
listed: false
copyedit: false
last_tested: "2025-01-01"
steps:
  - title: Step 1
  - title: Step 2
    completion:
      - engaged      
  - title: Step 3
  - title: Step 4
  - title: Step 5
  - title: Step 6
  - title: Step 7
  - title: Step 8
    completion:
      - internal
  - title: Step 9
    challenge: true
    completion:
      - external
