title: Editor storytime
hero_image: images/banner.png
description: default-project-template description
version: 1
listed: false
copyedit: false
last_tested: "2025-01-01"
steps:
  - title: What you will make
  - title: Output your first line
    completion:
      - engaged      
  - title: Get the dragon's name
  - title: Join the story parts
  - title: Size and age of the dragon
  - title: Is the dragon old?
  - title: Add some random details
  - title: Add MORE random details!
  - title: Choose random details
  - title: Tell your story
    completion:
      - internal
  - title: Challenge
    challenge: true
    completion:
      - external
